// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {adb} from '../models';
import {main} from '../models';

export function ADBVersion():Promise<string>;

export function AddForward(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AddReverse(arg1:string,arg2:string,arg3:string):Promise<string>;

export function AdoptExternalCapture(arg1:string):Promise<void>;

export function AndroidVersionMap():Promise<Record<number, string>>;

export function AppIcon(arg1:string,arg2:string):Promise<string>;

export function AppendIptablesRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<adb.IPTSnapshot>;

export function ApplyHostsConfig(arg1:string):Promise<adb.HostsApplyResult>;

export function ApplyProfile(arg1:string,arg2:string):Promise<adb.ApplyReport>;

export function BindDeviceProfile(arg1:string,arg2:string):Promise<void>;

export function BindDeviceProfileByKey(arg1:string,arg2:string):Promise<void>;

export function BrowseCodeshare(arg1:number):Promise<Array<adb.CodeshareProject>>;

export function CancelTask(arg1:string):Promise<void>;

export function CaptureProfileFromDevice(arg1:string,arg2:string):Promise<adb.Profile>;

export function CaptureStatus(arg1:string):Promise<adb.CaptureState>;

export function ChmodFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ChownFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function ClearApp(arg1:string,arg2:string):Promise<string>;

export function ClearFridaHistory():Promise<void>;

export function ClearLogcat(arg1:string):Promise<string>;

export function ClearShellHistory(arg1:string,arg2:string):Promise<void>;

export function ClipboardSet(arg1:string,arg2:string):Promise<string>;

export function CloseShell(arg1:string):Promise<void>;

export function ConnectTCP(arg1:string):Promise<string>;

export function CreateIptablesChain(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DNSLookup(arg1:string,arg2:string):Promise<string>;

export function DeleteFile(arg1:string,arg2:string,arg3:boolean,arg4:boolean):Promise<string>;

export function DeleteFridaScript(arg1:string):Promise<void>;

export function DeleteIptablesChain(arg1:string,arg2:string,arg3:string,arg4:string):Promise<void>;

export function DeleteIptablesRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<adb.IPTSnapshot>;

export function DeleteProfile(arg1:string):Promise<void>;

export function DescribeApp(arg1:string,arg2:string):Promise<adb.AppDetail>;

export function DescribeLivePacket(arg1:string,arg2:number):Promise<adb.LivePacketDetail>;

export function DetectRunningFridaVersion(arg1:string):Promise<string>;

export function DeviceDetails(arg1:string):Promise<adb.Device>;

export function DeviceKey(arg1:string):Promise<string>;

export function DisconnectDevice(arg1:string):Promise<string>;

export function EnsureFridaVenv(arg1:string):Promise<adb.FridaRuntime>;

export function EnsureLogcat(arg1:string,arg2:string,arg3:boolean):Promise<boolean>;

export function ExportAPK(arg1:string,arg2:string):Promise<string>;

export function ExportAppDataWithPicker(arg1:string,arg2:string):Promise<string>;

export function ExportIptables(arg1:string,arg2:string):Promise<string>;

export function FlushDeviceDNS(arg1:string):Promise<string>;

export function FlushIptables(arg1:string,arg2:string,arg3:string,arg4:string):Promise<adb.IPTSnapshot>;

export function ForceStopApp(arg1:string,arg2:string):Promise<string>;

export function FridaArchInfo(arg1:string):Promise<adb.FridaArchInfo>;

export function FridaHost():Promise<adb.FridaHostInfo>;

export function FridaManagedEnabled():Promise<boolean>;

export function FridaServerLog(arg1:string):Promise<string>;

export function GetAppFridaScripts(arg1:string):Promise<adb.AppScripts>;

export function GetCodeshareScript(arg1:string,arg2:string):Promise<adb.CodeshareScript>;

export function GetFridaScript(arg1:string):Promise<adb.FridaScript>;

export function GetFridaSessionLog(arg1:string,arg2:number):Promise<Array<adb.FridaMsg>>;

export function GetNetworkInfo(arg1:string):Promise<adb.NetworkInfo>;

export function GetProfile(arg1:string):Promise<adb.Profile>;

export function GetProxy(arg1:string):Promise<string>;

export function GetStats(arg1:string):Promise<adb.Stats>;

export function HostLANIPs(arg1:string):Promise<Array<string>>;

export function HostsDrifted(arg1:string):Promise<boolean>;

export function ImportCodeshareScript(arg1:string,arg2:string):Promise<adb.FridaScript>;

export function ImportIptables(arg1:string,arg2:string,arg3:string):Promise<void>;

export function InsertIptablesRule(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number,arg6:Array<string>):Promise<adb.IPTSnapshot>;

export function InstallAPKFromPath(arg1:string,arg2:string):Promise<string>;

export function InstallFridaServer(arg1:string,arg2:string,arg3:string):Promise<string>;

export function InstallSystemCertWithPicker(arg1:string):Promise<adb.CertInstallResult>;

export function InstallTcpdumpAuto(arg1:string,arg2:boolean):Promise<adb.TcpdumpInfo>;

export function InstallTcpdumpWithPicker(arg1:string):Promise<adb.TcpdumpInfo>;

export function IsAppRunning(arg1:string,arg2:string):Promise<adb.AppRunning>;

export function KillExternalCapture(arg1:string):Promise<adb.CaptureState>;

export function LaunchApp(arg1:string,arg2:string):Promise<string>;

export function ListAppFridaScripts():Promise<Array<adb.AppScripts>>;

export function ListApps(arg1:string,arg2:boolean):Promise<Array<adb.App>>;

export function ListCACerts(arg1:string):Promise<Array<adb.CACert>>;

export function ListConnections(arg1:string):Promise<Array<adb.Connection>>;

export function ListDeviceRecords():Promise<Array<adb.DeviceRecord>>;

export function ListDevices():Promise<Array<adb.Device>>;

export function ListDir(arg1:string,arg2:string,arg3:boolean):Promise<Array<adb.FileEntry>>;

export function ListForwards(arg1:string):Promise<Array<adb.Forward>>;

export function ListFridaHistory():Promise<Array<adb.FridaHistoryEntry>>;

export function ListFridaReleases(arg1:string,arg2:string):Promise<Array<adb.FridaRelease>>;

export function ListFridaRuntimes():Promise<Array<adb.FridaRuntime>>;

export function ListFridaScripts():Promise<Array<adb.FridaScript>>;

export function ListFridaServers(arg1:string):Promise<Array<adb.FridaServer>>;

export function ListFridaSessions():Promise<Array<adb.FridaSessionInfo>>;

export function ListIptables(arg1:string,arg2:string,arg3:string):Promise<adb.IPTSnapshot>;

export function ListPackageUIDs(arg1:string):Promise<Record<number, string>>;

export function ListProfiles():Promise<Array<adb.Profile>>;

export function ListReverses(arg1:string):Promise<Array<adb.Forward>>;

export function ListShellHistory():Promise<Array<adb.ScrollbackEntry>>;

export function ListTasks():Promise<Array<adb.TaskState>>;

export function LiveCaptureStatus(arg1:string):Promise<adb.LiveCaptureState>;

export function LoadHostsConfig(arg1:string):Promise<string>;

export function LookupDeviceProfile(arg1:string):Promise<string>;

export function Mkdir(arg1:string,arg2:string,arg3:boolean):Promise<string>;

export function MoveFile(arg1:string,arg2:string,arg3:string,arg4:boolean):Promise<string>;

export function OpenPath(arg1:string):Promise<void>;

export function OpenShell(arg1:string,arg2:boolean):Promise<string>;

export function PickAndInstallAPK(arg1:string):Promise<string>;

export function PickExternalFridaInterpreter():Promise<adb.FridaRuntime>;

export function PlanTcpdumpAutoInstall(arg1:string):Promise<adb.TcpdumpAutoPlan>;

export function PreviewProfile(arg1:string,arg2:string):Promise<Array<adb.StepPreview>>;

export function ProbeIptables(arg1:string,arg2:string):Promise<adb.IPTBackendInfo>;

export function ProbeTcpdump(arg1:string):Promise<adb.TcpdumpInfo>;

export function PullCapture(arg1:string):Promise<string>;

export function PullFileWithPicker(arg1:string,arg2:string):Promise<string>;

export function PushFileWithOptions(arg1:string,arg2:string,arg3:string,arg4:string,arg5:boolean):Promise<string>;

export function PushFileWithPicker(arg1:string,arg2:string):Promise<string>;

export function PushFridaBinaryWithPicker(arg1:string):Promise<string>;

export function ReadShellHistory(arg1:string,arg2:string):Promise<string>;

export function Reboot(arg1:string,arg2:string):Promise<string>;

export function RecordingActive(arg1:string):Promise<boolean>;

export function RegisterDevice(arg1:adb.Device):Promise<void>;

export function RegisterExternalFrida(arg1:string):Promise<adb.FridaRuntime>;

export function RemoveForward(arg1:string,arg2:string):Promise<string>;

export function RemoveFridaHistory(arg1:string):Promise<void>;

export function RemoveFridaRuntime(arg1:string):Promise<void>;

export function RemoveFridaSession(arg1:string):Promise<void>;

export function RemoveReverse(arg1:string,arg2:string):Promise<string>;

export function RemoveTask(arg1:string):Promise<void>;

export function ResizeShell(arg1:string,arg2:number,arg3:number):Promise<void>;

export function RevealPath(arg1:string):Promise<void>;

export function RunCommand(arg1:string,arg2:string):Promise<string>;

export function RunCommandRoot(arg1:string,arg2:string):Promise<string>;

export function SaveFridaScript(arg1:adb.FridaScript):Promise<adb.FridaScript>;

export function SaveHostsConfig(arg1:string,arg2:string):Promise<void>;

export function SaveLivePcap(arg1:string):Promise<string>;

export function SaveProfile(arg1:adb.Profile):Promise<adb.Profile>;

export function SaveScreenshotAs(arg1:string):Promise<string>;

export function ScrcpyActive(arg1:string):Promise<boolean>;

export function ScrcpyAvailable():Promise<boolean>;

export function ScreenRecord(arg1:string,arg2:number):Promise<string>;

export function SearchCodeshare(arg1:string):Promise<Array<adb.CodeshareProject>>;

export function SetAppFridaScripts(arg1:string,arg2:Array<string>,arg3:string,arg4:string):Promise<void>;

export function SetFridaManagedEnabled(arg1:boolean):Promise<void>;

export function SetIptablesPolicy(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function SetLogcatSystem(arg1:string,arg2:boolean):Promise<void>;

export function SetProxy(arg1:string,arg2:string):Promise<string>;

export function StartAppWithFrida(arg1:string,arg2:string,arg3:string):Promise<adb.FridaSessionInfo>;

export function StartCapture(arg1:string,arg2:string,arg3:string):Promise<adb.CaptureState>;

export function StartDNSSniffer(arg1:string):Promise<main.DNSSnifferStatus>;

export function StartFrida(arg1:string,arg2:string,arg3:string,arg4:number):Promise<string>;

export function StartFridaSession(arg1:string,arg2:string,arg3:string,arg4:string,arg5:Array<string>):Promise<adb.FridaSessionInfo>;

export function StartLiveCapture(arg1:string,arg2:string,arg3:string,arg4:adb.LiveCaptureOptions):Promise<adb.LiveCaptureState>;

export function StartProcStream(arg1:string,arg2:number):Promise<main.ProcStreamStatus>;

export function StartScrcpy(arg1:string):Promise<void>;

export function StartScreenRecord(arg1:string,arg2:number):Promise<string>;

export function StopCapture(arg1:string):Promise<adb.CaptureState>;

export function StopDNSSniffer(arg1:string):Promise<void>;

export function StopFrida(arg1:string):Promise<string>;

export function StopFridaSession(arg1:string):Promise<void>;

export function StopLiveCapture(arg1:string):Promise<void>;

export function StopLogcat(arg1:string):Promise<void>;

export function StopProcStream(arg1:string):Promise<void>;

export function StopScrcpy(arg1:string):Promise<void>;

export function StopScreenRecord(arg1:string):Promise<string>;

export function SuggestProxyHost(arg1:string,arg2:number):Promise<main.ProxySuggestion>;

export function TakeScreenshot(arg1:string):Promise<string>;

export function TcpipMode(arg1:string,arg2:number):Promise<string>;

export function UndoIptables(arg1:string,arg2:string):Promise<adb.IPTSnapshot>;

export function UninstallApp(arg1:string,arg2:string):Promise<string>;

export function Version():Promise<string>;

export function WriteShell(arg1:string,arg2:string):Promise<void>;
