// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ADBVersion() {
  return window['go']['main']['App']['ADBVersion']();
}

export function AddForward(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddForward'](arg1, arg2, arg3);
}

export function AddReverse(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddReverse'](arg1, arg2, arg3);
}

export function AdoptExternalCapture(arg1) {
  return window['go']['main']['App']['AdoptExternalCapture'](arg1);
}

export function AndroidVersionMap() {
  return window['go']['main']['App']['AndroidVersionMap']();
}

export function AppIcon(arg1, arg2) {
  return window['go']['main']['App']['AppIcon'](arg1, arg2);
}

export function AppendIptablesRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['AppendIptablesRule'](arg1, arg2, arg3, arg4, arg5);
}

export function ApplyHostsConfig(arg1) {
  return window['go']['main']['App']['ApplyHostsConfig'](arg1);
}

export function ApplyProfile(arg1, arg2) {
  return window['go']['main']['App']['ApplyProfile'](arg1, arg2);
}

export function BindDeviceProfile(arg1, arg2) {
  return window['go']['main']['App']['BindDeviceProfile'](arg1, arg2);
}

export function BindDeviceProfileByKey(arg1, arg2) {
  return window['go']['main']['App']['BindDeviceProfileByKey'](arg1, arg2);
}

export function BrowseCodeshare(arg1) {
  return window['go']['main']['App']['BrowseCodeshare'](arg1);
}

export function CancelTask(arg1) {
  return window['go']['main']['App']['CancelTask'](arg1);
}

export function CaptureProfileFromDevice(arg1, arg2) {
  return window['go']['main']['App']['CaptureProfileFromDevice'](arg1, arg2);
}

export function CaptureStatus(arg1) {
  return window['go']['main']['App']['CaptureStatus'](arg1);
}

export function ChmodFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChmodFile'](arg1, arg2, arg3, arg4);
}

export function ChownFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ChownFile'](arg1, arg2, arg3, arg4);
}

export function ClearApp(arg1, arg2) {
  return window['go']['main']['App']['ClearApp'](arg1, arg2);
}

export function ClearFridaHistory() {
  return window['go']['main']['App']['ClearFridaHistory']();
}

export function ClearLogcat(arg1) {
  return window['go']['main']['App']['ClearLogcat'](arg1);
}

export function ClearShellHistory(arg1, arg2) {
  return window['go']['main']['App']['ClearShellHistory'](arg1, arg2);
}

export function ClipboardSet(arg1, arg2) {
  return window['go']['main']['App']['ClipboardSet'](arg1, arg2);
}

export function CloseShell(arg1) {
  return window['go']['main']['App']['CloseShell'](arg1);
}

export function ConnectTCP(arg1) {
  return window['go']['main']['App']['ConnectTCP'](arg1);
}

export function CreateIptablesChain(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['CreateIptablesChain'](arg1, arg2, arg3, arg4);
}

export function DNSLookup(arg1, arg2) {
  return window['go']['main']['App']['DNSLookup'](arg1, arg2);
}

export function DeleteFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteFile'](arg1, arg2, arg3, arg4);
}

export function DeleteFridaScript(arg1) {
  return window['go']['main']['App']['DeleteFridaScript'](arg1);
}

export function DeleteIptablesChain(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['DeleteIptablesChain'](arg1, arg2, arg3, arg4);
}

export function DeleteIptablesRule(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DeleteIptablesRule'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DescribeApp(arg1, arg2) {
  return window['go']['main']['App']['DescribeApp'](arg1, arg2);
}

export function DescribeLivePacket(arg1, arg2) {
  return window['go']['main']['App']['DescribeLivePacket'](arg1, arg2);
}

export function DetectRunningFridaVersion(arg1) {
  return window['go']['main']['App']['DetectRunningFridaVersion'](arg1);
}

export function DeviceDetails(arg1) {
  return window['go']['main']['App']['DeviceDetails'](arg1);
}

export function DeviceKey(arg1) {
  return window['go']['main']['App']['DeviceKey'](arg1);
}

export function DisconnectDevice(arg1) {
  return window['go']['main']['App']['DisconnectDevice'](arg1);
}

export function EnsureFridaVenv(arg1) {
  return window['go']['main']['App']['EnsureFridaVenv'](arg1);
}

export function EnsureLogcat(arg1, arg2, arg3) {
  return window['go']['main']['App']['EnsureLogcat'](arg1, arg2, arg3);
}

export function ExportAPK(arg1, arg2) {
  return window['go']['main']['App']['ExportAPK'](arg1, arg2);
}

export function ExportAppDataWithPicker(arg1, arg2) {
  return window['go']['main']['App']['ExportAppDataWithPicker'](arg1, arg2);
}

export function ExportIptables(arg1, arg2) {
  return window['go']['main']['App']['ExportIptables'](arg1, arg2);
}

export function FlushDeviceDNS(arg1) {
  return window['go']['main']['App']['FlushDeviceDNS'](arg1);
}

export function FlushIptables(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FlushIptables'](arg1, arg2, arg3, arg4);
}

export function ForceStopApp(arg1, arg2) {
  return window['go']['main']['App']['ForceStopApp'](arg1, arg2);
}

export function FridaArchInfo(arg1) {
  return window['go']['main']['App']['FridaArchInfo'](arg1);
}

export function FridaHost() {
  return window['go']['main']['App']['FridaHost']();
}

export function FridaManagedEnabled() {
  return window['go']['main']['App']['FridaManagedEnabled']();
}

export function FridaServerLog(arg1, arg2) {
  return window['go']['main']['App']['FridaServerLog'](arg1, arg2);
}

export function GetAppFridaScripts(arg1) {
  return window['go']['main']['App']['GetAppFridaScripts'](arg1);
}

export function GetCodeshareScript(arg1, arg2) {
  return window['go']['main']['App']['GetCodeshareScript'](arg1, arg2);
}

export function GetFridaScript(arg1) {
  return window['go']['main']['App']['GetFridaScript'](arg1);
}

export function GetFridaSessionLog(arg1, arg2) {
  return window['go']['main']['App']['GetFridaSessionLog'](arg1, arg2);
}

export function GetNetworkInfo(arg1) {
  return window['go']['main']['App']['GetNetworkInfo'](arg1);
}

export function GetProfile(arg1) {
  return window['go']['main']['App']['GetProfile'](arg1);
}

export function GetProxy(arg1) {
  return window['go']['main']['App']['GetProxy'](arg1);
}

export function GetStats(arg1) {
  return window['go']['main']['App']['GetStats'](arg1);
}

export function HostLANIPs(arg1) {
  return window['go']['main']['App']['HostLANIPs'](arg1);
}

export function HostsDrifted(arg1) {
  return window['go']['main']['App']['HostsDrifted'](arg1);
}

export function ImportCodeshareScript(arg1, arg2) {
  return window['go']['main']['App']['ImportCodeshareScript'](arg1, arg2);
}

export function ImportIptables(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportIptables'](arg1, arg2, arg3);
}

export function InsertIptablesRule(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['InsertIptablesRule'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function InstallAPKFromPath(arg1, arg2) {
  return window['go']['main']['App']['InstallAPKFromPath'](arg1, arg2);
}

export function InstallFridaServer(arg1, arg2, arg3) {
  return window['go']['main']['App']['InstallFridaServer'](arg1, arg2, arg3);
}

export function InstallSystemCertWithPicker(arg1) {
  return window['go']['main']['App']['InstallSystemCertWithPicker'](arg1);
}

export function InstallTcpdumpAuto(arg1, arg2) {
  return window['go']['main']['App']['InstallTcpdumpAuto'](arg1, arg2);
}

export function InstallTcpdumpWithPicker(arg1) {
  return window['go']['main']['App']['InstallTcpdumpWithPicker'](arg1);
}

export function IsAppRunning(arg1, arg2) {
  return window['go']['main']['App']['IsAppRunning'](arg1, arg2);
}

export function KillExternalCapture(arg1) {
  return window['go']['main']['App']['KillExternalCapture'](arg1);
}

export function LaunchApp(arg1, arg2) {
  return window['go']['main']['App']['LaunchApp'](arg1, arg2);
}

export function ListAppFridaScripts() {
  return window['go']['main']['App']['ListAppFridaScripts']();
}

export function ListApps(arg1, arg2) {
  return window['go']['main']['App']['ListApps'](arg1, arg2);
}

export function ListCACerts(arg1) {
  return window['go']['main']['App']['ListCACerts'](arg1);
}

export function ListConnections(arg1) {
  return window['go']['main']['App']['ListConnections'](arg1);
}

export function ListDeviceRecords() {
  return window['go']['main']['App']['ListDeviceRecords']();
}

export function ListDevices() {
  return window['go']['main']['App']['ListDevices']();
}

export function ListDir(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListDir'](arg1, arg2, arg3);
}

export function ListForwards(arg1) {
  return window['go']['main']['App']['ListForwards'](arg1);
}

export function ListFridaHistory() {
  return window['go']['main']['App']['ListFridaHistory']();
}

export function ListFridaReleases(arg1, arg2) {
  return window['go']['main']['App']['ListFridaReleases'](arg1, arg2);
}

export function ListFridaRuntimes() {
  return window['go']['main']['App']['ListFridaRuntimes']();
}

export function ListFridaScripts() {
  return window['go']['main']['App']['ListFridaScripts']();
}

export function ListFridaServers(arg1) {
  return window['go']['main']['App']['ListFridaServers'](arg1);
}

export function ListFridaSessions() {
  return window['go']['main']['App']['ListFridaSessions']();
}

export function ListIptables(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListIptables'](arg1, arg2, arg3);
}

export function ListPackageUIDs(arg1) {
  return window['go']['main']['App']['ListPackageUIDs'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function ListReverses(arg1) {
  return window['go']['main']['App']['ListReverses'](arg1);
}

export function ListShellHistory() {
  return window['go']['main']['App']['ListShellHistory']();
}

export function ListTasks() {
  return window['go']['main']['App']['ListTasks']();
}

export function LiveCaptureStatus(arg1) {
  return window['go']['main']['App']['LiveCaptureStatus'](arg1);
}

export function LoadHostsConfig(arg1) {
  return window['go']['main']['App']['LoadHostsConfig'](arg1);
}

export function LookupDeviceProfile(arg1) {
  return window['go']['main']['App']['LookupDeviceProfile'](arg1);
}

export function Mkdir(arg1, arg2, arg3) {
  return window['go']['main']['App']['Mkdir'](arg1, arg2, arg3);
}

export function MoveFile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MoveFile'](arg1, arg2, arg3, arg4);
}

export function OpenPath(arg1) {
  return window['go']['main']['App']['OpenPath'](arg1);
}

export function OpenShell(arg1, arg2) {
  return window['go']['main']['App']['OpenShell'](arg1, arg2);
}

export function PickAndInstallAPK(arg1) {
  return window['go']['main']['App']['PickAndInstallAPK'](arg1);
}

export function PickExternalFridaInterpreter() {
  return window['go']['main']['App']['PickExternalFridaInterpreter']();
}

export function PlanTcpdumpAutoInstall(arg1) {
  return window['go']['main']['App']['PlanTcpdumpAutoInstall'](arg1);
}

export function PreviewProfile(arg1, arg2) {
  return window['go']['main']['App']['PreviewProfile'](arg1, arg2);
}

export function ProbeIptables(arg1, arg2) {
  return window['go']['main']['App']['ProbeIptables'](arg1, arg2);
}

export function ProbeTcpdump(arg1) {
  return window['go']['main']['App']['ProbeTcpdump'](arg1);
}

export function PullCapture(arg1) {
  return window['go']['main']['App']['PullCapture'](arg1);
}

export function PullFileWithPicker(arg1, arg2) {
  return window['go']['main']['App']['PullFileWithPicker'](arg1, arg2);
}

export function PushFileWithOptions(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['PushFileWithOptions'](arg1, arg2, arg3, arg4, arg5);
}

export function PushFileWithPicker(arg1, arg2) {
  return window['go']['main']['App']['PushFileWithPicker'](arg1, arg2);
}

export function PushFridaBinaryWithPicker(arg1) {
  return window['go']['main']['App']['PushFridaBinaryWithPicker'](arg1);
}

export function ReadShellHistory(arg1, arg2) {
  return window['go']['main']['App']['ReadShellHistory'](arg1, arg2);
}

export function Reboot(arg1, arg2) {
  return window['go']['main']['App']['Reboot'](arg1, arg2);
}

export function RecordingActive(arg1) {
  return window['go']['main']['App']['RecordingActive'](arg1);
}

export function RegisterDevice(arg1) {
  return window['go']['main']['App']['RegisterDevice'](arg1);
}

export function RegisterExternalFrida(arg1) {
  return window['go']['main']['App']['RegisterExternalFrida'](arg1);
}

export function RemoveForward(arg1, arg2) {
  return window['go']['main']['App']['RemoveForward'](arg1, arg2);
}

export function RemoveFridaHistory(arg1) {
  return window['go']['main']['App']['RemoveFridaHistory'](arg1);
}

export function RemoveFridaRuntime(arg1) {
  return window['go']['main']['App']['RemoveFridaRuntime'](arg1);
}

export function RemoveFridaSession(arg1) {
  return window['go']['main']['App']['RemoveFridaSession'](arg1);
}

export function RemoveReverse(arg1, arg2) {
  return window['go']['main']['App']['RemoveReverse'](arg1, arg2);
}

export function RemoveTask(arg1) {
  return window['go']['main']['App']['RemoveTask'](arg1);
}

export function ResizeShell(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResizeShell'](arg1, arg2, arg3);
}

export function RevealPath(arg1) {
  return window['go']['main']['App']['RevealPath'](arg1);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function RunCommandRoot(arg1, arg2) {
  return window['go']['main']['App']['RunCommandRoot'](arg1, arg2);
}

export function SaveFridaScript(arg1) {
  return window['go']['main']['App']['SaveFridaScript'](arg1);
}

export function SaveHostsConfig(arg1, arg2) {
  return window['go']['main']['App']['SaveHostsConfig'](arg1, arg2);
}

export function SaveLivePcap(arg1) {
  return window['go']['main']['App']['SaveLivePcap'](arg1);
}

export function SaveProfile(arg1) {
  return window['go']['main']['App']['SaveProfile'](arg1);
}

export function SaveScreenshotAs(arg1) {
  return window['go']['main']['App']['SaveScreenshotAs'](arg1);
}

export function ScrcpyActive(arg1) {
  return window['go']['main']['App']['ScrcpyActive'](arg1);
}

export function ScrcpyAvailable() {
  return window['go']['main']['App']['ScrcpyAvailable']();
}

export function ScreenRecord(arg1, arg2) {
  return window['go']['main']['App']['ScreenRecord'](arg1, arg2);
}

export function SearchCodeshare(arg1) {
  return window['go']['main']['App']['SearchCodeshare'](arg1);
}

export function SetAppFridaScripts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SetAppFridaScripts'](arg1, arg2, arg3, arg4);
}

export function SetFridaManagedEnabled(arg1) {
  return window['go']['main']['App']['SetFridaManagedEnabled'](arg1);
}

export function SetIptablesPolicy(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['SetIptablesPolicy'](arg1, arg2, arg3, arg4, arg5);
}

export function SetLogcatSystem(arg1, arg2) {
  return window['go']['main']['App']['SetLogcatSystem'](arg1, arg2);
}

export function SetProxy(arg1, arg2) {
  return window['go']['main']['App']['SetProxy'](arg1, arg2);
}

export function StartAppWithFrida(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartAppWithFrida'](arg1, arg2, arg3);
}

export function StartCapture(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartCapture'](arg1, arg2, arg3);
}

export function StartDNSSniffer(arg1) {
  return window['go']['main']['App']['StartDNSSniffer'](arg1);
}

export function StartFrida(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartFrida'](arg1, arg2, arg3, arg4);
}

export function StartFridaSession(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['StartFridaSession'](arg1, arg2, arg3, arg4, arg5);
}

export function StartLiveCapture(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['StartLiveCapture'](arg1, arg2, arg3, arg4);
}

export function StartProcStream(arg1, arg2) {
  return window['go']['main']['App']['StartProcStream'](arg1, arg2);
}

export function StartScrcpy(arg1) {
  return window['go']['main']['App']['StartScrcpy'](arg1);
}

export function StartScreenRecord(arg1, arg2) {
  return window['go']['main']['App']['StartScreenRecord'](arg1, arg2);
}

export function StopCapture(arg1) {
  return window['go']['main']['App']['StopCapture'](arg1);
}

export function StopDNSSniffer(arg1) {
  return window['go']['main']['App']['StopDNSSniffer'](arg1);
}

export function StopFrida(arg1) {
  return window['go']['main']['App']['StopFrida'](arg1);
}

export function StopFridaSession(arg1) {
  return window['go']['main']['App']['StopFridaSession'](arg1);
}

export function StopLiveCapture(arg1) {
  return window['go']['main']['App']['StopLiveCapture'](arg1);
}

export function StopLogcat(arg1) {
  return window['go']['main']['App']['StopLogcat'](arg1);
}

export function StopProcStream(arg1) {
  return window['go']['main']['App']['StopProcStream'](arg1);
}

export function StopScrcpy(arg1) {
  return window['go']['main']['App']['StopScrcpy'](arg1);
}

export function StopScreenRecord(arg1) {
  return window['go']['main']['App']['StopScreenRecord'](arg1);
}

export function SuggestProxyHost(arg1, arg2) {
  return window['go']['main']['App']['SuggestProxyHost'](arg1, arg2);
}

export function TakeScreenshot(arg1) {
  return window['go']['main']['App']['TakeScreenshot'](arg1);
}

export function TcpipMode(arg1, arg2) {
  return window['go']['main']['App']['TcpipMode'](arg1, arg2);
}

export function UndoIptables(arg1, arg2) {
  return window['go']['main']['App']['UndoIptables'](arg1, arg2);
}

export function UninstallApp(arg1, arg2) {
  return window['go']['main']['App']['UninstallApp'](arg1, arg2);
}

export function Version() {
  return window['go']['main']['App']['Version']();
}

export function WriteShell(arg1, arg2) {
  return window['go']['main']['App']['WriteShell'](arg1, arg2);
}
